id: I4DD472AA
ocr_import_info:
  source: bdrc
  software: google_books
  batch: batch_2022
  expected_default_language: bo
  bdrc_scan_id: W7477
  ocr_info:
    timestamp: 11/17/22T21:22:40
    html: html.zip
    txt: txt.zip
    images: images.zip
  op_import_options: {}
  op_import_version: 0.11.9
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2024-03-05 04:26:21.814445+00:00
last_modified: 2024-03-05 04:26:21.814451+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W7477
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW7477
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་འབུམ། འཇིགས་མེད་གླིང་པ ༼ཨ་འཛོམ་པར་མ། འབྲུག་སྤ་གྲོ་ལ་བསྐྱར་པར་བརྒྱབ་པ།༽
  languages:
  - bo
  author: ཀུན་མཁྱེན་འཇིགས་མེད་གླིང་པ།
statistics:
  ocr_word_mean_confidence_index: 0.9548390344330727
  ocr_word_median_confidence_index: 1.0
bases:
  I0659:
    source_metadata:
      id: http://purl.bdrc.io/resource/I0659
      total_pages: 777
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I0659.txt
    statistics:
      ocr_word_median_confidence_index: 1.0
      ocr_word_mean_confidence_index: 0.9694566388365203
  I0660:
    source_metadata:
      id: http://purl.bdrc.io/resource/I0660
      total_pages: 685
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I0660.txt
    statistics:
      ocr_word_median_confidence_index: 1.0
      ocr_word_mean_confidence_index: 0.9668843387178193
  I0661:
    source_metadata:
      id: http://purl.bdrc.io/resource/I0661
      total_pages: 731
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I0661.txt
    statistics:
      ocr_word_median_confidence_index: 1.0
      ocr_word_mean_confidence_index: 0.9675893884285997
  I0662:
    source_metadata:
      id: http://purl.bdrc.io/resource/I0662
      total_pages: 784
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I0662.txt
    statistics:
      ocr_word_median_confidence_index: 1.0
      ocr_word_mean_confidence_index: 0.9644521578224795
  I0663:
    source_metadata:
      id: http://purl.bdrc.io/resource/I0663
      total_pages: 769
      volume_number: 5
      volume_pages_bdrc_intro: 2
    order: 5
    base_file: I0663.txt
    statistics:
      ocr_word_median_confidence_index: 1.0
      ocr_word_mean_confidence_index: 0.9628253316154106
  I0664:
    source_metadata:
      id: http://purl.bdrc.io/resource/I0664
      total_pages: 737
      volume_number: 6
      volume_pages_bdrc_intro: 2
    order: 6
    base_file: I0664.txt
    statistics:
      ocr_word_median_confidence_index: 1.0
      ocr_word_mean_confidence_index: 0.9537355775680872
  I0665:
    source_metadata:
      id: http://purl.bdrc.io/resource/I0665
      total_pages: 805
      volume_number: 7
      volume_pages_bdrc_intro: 2
    order: 7
    base_file: I0665.txt
    statistics:
      ocr_word_median_confidence_index: 1.0
      ocr_word_mean_confidence_index: 0.9637496955447636
  I0666:
    source_metadata:
      id: http://purl.bdrc.io/resource/I0666
      total_pages: 723
      volume_number: 8
      volume_pages_bdrc_intro: 2
    order: 8
    base_file: I0666.txt
    statistics:
      ocr_word_median_confidence_index: 1.0
      ocr_word_mean_confidence_index: 0.9453138039210852
  I0667:
    source_metadata:
      id: http://purl.bdrc.io/resource/I0667
      total_pages: 725
      volume_number: 9
      volume_pages_bdrc_intro: 2
    order: 9
    base_file: I0667.txt
    statistics:
      ocr_word_median_confidence_index: 1.0
      ocr_word_mean_confidence_index: 0.9466033869179279
  I0668:
    source_metadata:
      id: http://purl.bdrc.io/resource/I0668
      total_pages: 711
      volume_number: 10
      volume_pages_bdrc_intro: 2
    order: 10
    base_file: I0668.txt
    statistics:
      ocr_word_median_confidence_index: 1.0
      ocr_word_mean_confidence_index: 0.9297484399770635
  I0669:
    source_metadata:
      id: http://purl.bdrc.io/resource/I0669
      total_pages: 682
      volume_number: 11
      volume_pages_bdrc_intro: 2
    order: 11
    base_file: I0669.txt
    statistics:
      ocr_word_median_confidence_index: 1.0
      ocr_word_mean_confidence_index: 0.9248768597302207
  I0670:
    source_metadata:
      id: http://purl.bdrc.io/resource/I0670
      total_pages: 699
      volume_number: 12
      volume_pages_bdrc_intro: 2
    order: 12
    base_file: I0670.txt
    statistics:
      ocr_word_median_confidence_index: 1.0
      ocr_word_mean_confidence_index: 0.9526336098515716
  I0671:
    source_metadata:
      id: http://purl.bdrc.io/resource/I0671
      total_pages: 735
      volume_number: 13
      volume_pages_bdrc_intro: 2
    order: 13
    base_file: I0671.txt
    statistics:
      ocr_word_median_confidence_index: 1.0
      ocr_word_mean_confidence_index: 0.9542126483191965
  I0672:
    source_metadata:
      id: http://purl.bdrc.io/resource/I0672
      total_pages: 735
      volume_number: 14
      volume_pages_bdrc_intro: 2
    order: 14
    base_file: I0672.txt
    statistics:
      ocr_word_median_confidence_index: 1.0
      ocr_word_mean_confidence_index: 0.9545242126868065
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
